package org.tempuri;

import java.util.List;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;

import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
// !DO NOT EDIT THIS FILE!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 130224.1947.04102)

@WebService(wsdlLocation="http://localhost:7101/ServerFootball-ServerFootball-context-root/ServicesPort?WSDL",
  targetNamespace="http://tempuri.org/", name="Services")
@XmlSeeAlso(
  { org.tempuri.ObjectFactory.class })
public interface Services
{
  @WebMethod
  @Action(input="http://tempuri.org/Services/listRequest", output="http://tempuri.org/Services/listResponse")
  @ResponseWrapper(localName="listResponse", targetNamespace="http://tempuri.org/",
    className="org.tempuri.ListResponse")
  @RequestWrapper(localName="list", targetNamespace="http://tempuri.org/",
    className="org.tempuri.List")
  @WebResult(targetNamespace="")
  public List<org.tempuri.Footballer> list();

  @WebMethod
  @Action(input="http://tempuri.org/Services/deleteRequest", output="http://tempuri.org/Services/deleteResponse")
  @ResponseWrapper(localName="deleteResponse", targetNamespace="http://tempuri.org/",
    className="org.tempuri.DeleteResponse")
  @RequestWrapper(localName="delete", targetNamespace="http://tempuri.org/",
    className="org.tempuri.Delete")
  @WebResult(targetNamespace="")
  public boolean delete(@WebParam(targetNamespace="", name="arg0")
    String arg0);

  @WebMethod
  @Action(input="http://tempuri.org/Services/readRequest", output="http://tempuri.org/Services/readResponse")
  @ResponseWrapper(localName="readResponse", targetNamespace="http://tempuri.org/",
    className="org.tempuri.ReadResponse")
  @RequestWrapper(localName="read", targetNamespace="http://tempuri.org/",
    className="org.tempuri.Read")
  @WebResult(targetNamespace="")
  public org.tempuri.Footballer read(@WebParam(targetNamespace="", name="arg0")
    String arg0);

  @WebMethod
  @Action(input="http://tempuri.org/Services/createRequest", output="http://tempuri.org/Services/createResponse")
  @ResponseWrapper(localName="createResponse", targetNamespace="http://tempuri.org/",
    className="org.tempuri.CreateResponse")
  @RequestWrapper(localName="create", targetNamespace="http://tempuri.org/",
    className="org.tempuri.Create")
  @WebResult(targetNamespace="")
  public boolean create(@WebParam(targetNamespace="", name="arg0")
    org.tempuri.Footballer arg0);

  @WebMethod
  @Action(input="http://tempuri.org/Services/updateRequest", output="http://tempuri.org/Services/updateResponse")
  @ResponseWrapper(localName="updateResponse", targetNamespace="http://tempuri.org/",
    className="org.tempuri.UpdateResponse")
  @RequestWrapper(localName="update", targetNamespace="http://tempuri.org/",
    className="org.tempuri.Update")
  @WebResult(targetNamespace="")
  public boolean update(@WebParam(targetNamespace="", name="arg0")
    org.tempuri.Footballer arg0);
}
